name: Deploy Nginx Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v3

    - name: Instalar Docker via script oficial
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Subir ambiente com Docker Compose
      run: docker compose up -d

    - name: Verificar se o container Nginx esta rodando
      run: docker ps | grep nginx

    - name: Verificar conteudo do HTML
      run: |
        if grep -qE ".*Ola, Mundo!" site/index.html; then
          echo "Conteudo encontrado no HTML"
        else
          echo "Conteudo esperado NAO encontrado"
          exit 1
        fi
